### ISSUE TITLE
When you click Show All Components you get an error

### ISSUE THREAD

**Issue by elucidsoft** [CosmicWill/Material-Kit-Gatsby#1] opened 2019-01-06 19:04 UTC
Hello,

First thank you for this template, its great.  Would love to see instructions on how to add the PRO stuff from the PRO version. I think I can  just add the components, not sure I am still getting the hang of Gatsby.  But when I click the Show All Components in the menu it throws an error. I am not familiar enough with Gatsby yet to figure out exactly why.

**Comment by CosmicWill** [comment] 2019-01-23 21:12
Hey, Sorry for the really slow response. I'll look into it now and get back to you before the end of the day.

**Comment by CosmicWill** [comment] 2019-01-23 21:28
The All Components button in the menu is just a link to the homepage. So I am unsure why you would have got an issue.  If the issue was caused after adding some of the Pro version components it might be that you are missing some references. Also, this project uses Gatsby Links and you might have been with the link syntax used in the original kit. Please let me know if you see any other issues. As for now I will close the issue as I do not have enough information to replicate it or determine the cause. If you see the issue again or want some help figuring it out, just let me know

**Closed as completed by CosmicWill** 2019-01-23 21:28 UTC
